version: '3.5'

services:
  dummyhttp:
    image: "svenstaro/dummyhttp:1.1.3@sha256:7f755b3f846f86c459d3e517416122c3f05a1185b62ff08abf34dff9cc1a7d0c"
  crs:
    image: "owasp/modsecurity-crs:4-apache-202404131004@sha256:9c20dd4756378de04c3587911efdf37c15614403c0540e008f16ca1cdbc63cba"
    environment:
      PORT: 8080
      BACKEND: "http://dummyhttp:8080"
      MODSEC_RULE_ENGINE: "On"
      BLOCKING_PARANOIA: 4
      MODSEC_AUDIT_LOG_FORMAT: JSON
      MODSEC_AUDIT_LOG_TYPE: concurrent
      MODSEC_TMP_DIR: "/tmp"
      # Apache only
      SERVERNAME: _default_
      MODSEC_ERROR_LOG: "/dev/stderr"
      MODSEC_AUDIT_LOG: "/var/log/apache2/modsec_audit.log"
    hostname: crs
  nuclei:
    image: projectdiscovery/nuclei:latest@sha256:aa3a9c0894629405b5bbe644765dfffd6ff87b7663b5f1d64bcbc01341da335a
    hostname: nuclei
    container_name: nuclei
    command: -u http://crs:8080 -t http/cves -type http -stats -ni -sresp -jle output.json
    volumes:
      - ./output:/output:rw
    depends_on:
      - dummyhttp
      - crs
