package cmd

import (
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/coreruleset/project-seaweed/internal/reader"
	"github.com/coreruleset/project-seaweed/internal/templates"
	"github.com/spf13/cobra"
)

var (
	// A dsl gate that talks about the body wants the same thing a word matcher does,
	// written differently: contains(body, "..."), contains(tolower(body), "..."),
	// contains_all(body, "...", "..."). Two thirds of the gates the mock cannot satisfy
	// are this shape.
	dslBodyClause = regexp.MustCompile(`(?i)\bbody(?:_?\d+)?\b`)
	dslLiteral    = regexp.MustCompile(`'([^']*)'|"([^"]*)"`)
)

// bodyLiterals returns the strings a dsl expression expects to find in the body. An
// expression that also tests something else contributes its literals too: serving a
// string the gate did not strictly need only risks letting a payload through to the WAF,
// which is the point of the exercise.
func bodyLiterals(expression string) []string {
	if !dslBodyClause.MatchString(expression) {
		return nil
	}

	var found []string
	for _, match := range dslLiteral.FindAllStringSubmatch(expression, -1) {
		literal := match[1]
		if literal == "" {
			literal = match[2]
		}
		if literal != "" {
			found = append(found, literal)
		}
	}

	return found
}

func newGenMockCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gen-mock",
		Short: "Generate the mock backend page from Nuclei flow-gated templates",
		Long: "Collects every internal word matcher from templates that declare a `flow` gate " +
			"and writes them into a single HTML page. Serving that page for every path lets " +
			"flow-gated templates reach their payload step, so the WAF actually sees the attack.",
		RunE: runGenMock,
	}
	cmd.Flags().StringP("templates", "t", "nuclei-templates/http/cves", "path to the Nuclei templates to scan")
	cmd.Flags().StringP("out", "O", "mock/fingerprints.html", "path of the HTML page to write")

	return cmd
}

func runGenMock(cmd *cobra.Command, _ []string) error {
	templates, err := cmd.Flags().GetString("templates")
	if err != nil {
		return err
	}
	out, err := cmd.Flags().GetString("out")
	if err != nil {
		return err
	}

	words, err := collectGateWords(templates)
	if err != nil {
		return err
	}
	if len(words) == 0 {
		return fmt.Errorf("no flow gate words found under %q: is it a Nuclei templates directory?", templates)
	}

	if err := os.WriteFile(out, []byte(renderFingerprintPage(words)), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", out, err)
	}
	cmd.Printf("wrote %s with %d fingerprints from %s\n", out, len(words), templates)

	return nil
}

// collectGateWords returns the sorted, deduplicated set of words that flow-gated
// templates expect to find in a response body before they send their payload.
func collectGateWords(root string) ([]string, error) {
	unique := map[string]struct{}{}

	err := templates.Each(root, func(template templates.Template) {
		if template.Flow == "" {
			return
		}
		for _, request := range template.HTTP {
			for _, matcher := range request.Matchers {
				if !matcher.Internal {
					continue
				}
				for _, word := range matcher.Words {
					unique[word] = struct{}{}
				}
				for _, expression := range matcher.DSL {
					for _, literal := range bodyLiterals(expression) {
						unique[literal] = struct{}{}
					}
				}
			}
		}
	})
	if err != nil {
		return nil, err
	}

	words := make([]string, 0, len(unique))
	for word := range unique {
		words = append(words, word)
	}
	sort.Strings(words)

	return words, nil
}

func renderFingerprintPage(words []string) string {
	var page strings.Builder
	page.WriteString("<!DOCTYPE html>\n<html>\n<head><title>seaweed mock backend</title></head>\n<body>\n")
	page.WriteString("<!-- Generated by `seaweed gen-mock`; do not edit by hand. -->\n")
	page.WriteString("<h1>It works!</h1>\n")
	// The same constant the reporter looks for to decide whether a request reached the
	// backend, and the healthcheck greps to prove the WAF round-trips.
	page.WriteString("<p>" + reader.BackendMarker + "</p>\n")
	page.WriteString("<pre>\n")
	for _, word := range words {
		page.WriteString(word + "\n")
	}
	page.WriteString("</pre>\n</body>\n</html>\n")

	return page.String()
}
