name: manual_test

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Specify attack type using tags'
      out_file:
        description: 'name of the report file'
      format:
        description: 'format for the report'
      waf_url:
        description: 'URL for the waf to be tested'
      cve_id:
        description: 'comma separated CVE Ids to test'
      full_report:
        description: 'Boolean to generate full report'

jobs:
  Run:
    name: Project runner
    env:
      TAG: ${{ github.event.inputs.tags }}
      OUT_FILE: ${{ github.event.inputs.out_file }}
      FORMAT: ${{ github.event.inputs.format }}
      WAF_URL: ${{ github.event.inputs.waf_url }}
      CVE_ID: ${{ github.event.inputs.cve_id }}
      FULL_REPORT: ${{ github.event.inputs.full_report }}
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64
    - name: install poetry
      run: pip install poetry==1.1.13
    - name: install project
      run: poetry install --no-dev
    - name: run program
      run: poetry run project-seaweed tester
    - name: list files
      run: ls
