name: Tests
on: 
  push:
    paths:
      - 'src/**'
      - 'tests/**'
jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9','3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install nuclei
      # fetch nuclei v2.7.7 binary, unzip and add to path
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUCLEI_VERSION: '3.2.5'
      run: |
        gh release download -R projectdiscovery/nuclei v${{ env.NUCLEI_VERSION }} -p \"nuclei_${{ env.NUCLEI_VERSION }}_linux_amd64.zip\" -O nuclei.zip
        unzip nuclei.zip nuclei
        rm nuclei.zip
        echo "$PWD" >> "$GITHUB_PATH"
        ./nuclei -ut
 
    - run: nox -s tests
