name: Tests
on: 
  push:
    paths:
      - 'src/**'
      - 'tests/**'
jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8','3.9','3.10', '3.11']
    name: Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install nuclei
      # fetch nuclei v2.7.7 binary, unzip and add to path
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUCLEI_VERSION: '2.8.8'
      run: |
        gh release download -R projectdiscovery/nuclei v${NUCLEI_VERSION} -p \"nuclei_${NUCLEI_VERSION}_linux_amd64.zip\" -O nuclei.zip
        unzip nuclei.zip
        rm nuclei.zip
        echo "$PWD" >> "$GITHUB_PATH"
        ./nuclei -ut
 
    - run: nox -s tests
